### ISSUE TITLE
Convention for 3pt and 5pt schemes

### ISSUE THREAD

**Issue by jejjohnson** [louity/MQGeometry#1]
Hi, thank you for open-sourcing the repo. I've been working on the multilayer QG model in JAX and your work has been great for getting me started. 

I wanted to know if there was some sort of convention for which reconstruction method to use for the 3pt and 5pt schemes?
For example:
* [Flux 3pt](https://github.com/louity/MQGeometry/blob/main/flux.py#L27) -  has `linear` reconstructions for the 3pt
* [Flux 3pt + mask](https://github.com/louity/MQGeometry/blob/main/flux.py#L142) - has `wenoz` reconstructions for the 3pt
* [Flux 5pt](https://github.com/louity/MQGeometry/blob/main/flux.py#L75)  - has `linear` reconstructions for the 5pt but `wenoz` for the 3pt
* [Flux 5pt + Mask](https://github.com/louity/MQGeometry/blob/main/flux.py#L171) - has `linear` reconstructions for the 5pt **and** 3pt.

I am assuming that we can simply plug-in-play the reconstruction method of our choice, right? For example, for the 5pt flux, should we simply use `wenoz` for both the 3pt and 5pt or perhaps that's overkill...? 

Thank you again.

**Comment by louity** [comment]
Hi, you can chose actually: linear is cheaper but might create spurious oscillations. For the flux 5points, the 3pts flux in only computed near the boundary so linear is fine for this par.
