### ISSUE TITLE
Comment : Works on AMD MI210 GPU with ROCm 5.7

### ISSUE THREAD

**Issue by fluidnumericsJoe** [louity/MQGeometry#2]
@louity - Love this repository! I was able to get up and running fairly quickly. I also wanted to share that this works with ROCm 5.7 and AMD MI210 GPU. When installing `torch` you can simply point to the rocm index

```
pip3 install torch --index-url https://download.pytorch.org/whl/rocm5.6
```

Currently, `rocm5.6` is listed in the pytorch index, but doesn't seem to conflict with ROCm 5.7 .

**Comment by louity** [comment]
Thanks, added in Readme
