### ISSUE TITLE
Removing beta-plane vorticity when inverting for stream function

### ISSUE THREAD

**Issue by roxyboy** [louity/MQGeometry#3]
Hi @louity, thank you for developing and sharing this package!

I have a naive (and probably stupid) question: Why is the beta-plane vorticity not removed prior to computing the time stepping in stream function (`dpsi`) as done [here](https://github.com/louity/MQGeometry/blob/f36617c4a89eab2891bc7c90b3eceb9c808452c1/qgm.py#L207)?
I would have thought it would be `dq_i = self.interp_TP(dq - self.beta*v)`.

I am slightly confused because it is removed when inverting for the total [stream function (`psi`) itself](https://github.com/louity/MQGeometry/blob/f36617c4a89eab2891bc7c90b3eceb9c808452c1/qgm.py#L161).

**Comment by louity** [comment]
Because its and increment in time, the derivative in time of beta y is zero

**Comment by roxyboy** [comment]
Thank you for your quick reply :)
When you take [`dq = self.advection_rhs()`](https://github.com/louity/MQGeometry/blob/73db239deda83df28aec4254799b36778da6da6c/qgm.py#L204C9-L204C34), doesn't this include the term `beta v`, which has the units of tendency...?

**Comment by louity** [comment]
The term beta y is included in the initial PV, then it affects the tendecies since div (u q) depends on q which contains a beta y term

**Comment by roxyboy** [comment]
> The term beta y is included in the initial PV, then it affects the tendecies since div (u q) depends on q which contains a beta y term

This makes perfect sense. But then when you invert for `dpsi` from `dq`, wouldn't inverting `div(u q)` end up including the beta term in `dpsi` ?

**Comment by louity** [comment]
no, simply simplt apply dt (time derivative) to the QG elliptic equation, which commutes with other operators, and ou will have 
dt_psi = (Laplacian - A)^-1 dt(q - By) = (Delta - A)^-1 dt_q = = (Delta - A)^-1 (-div(uq))
since dt(By) = 0 and dt_q = -div(uq)

**Comment by roxyboy** [comment]
Ah, makes sense. Thank you very much for the detailed explanation :)
